# Generated by Django 5.1.7 on 2025-04-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0002_userprofile_bio_alter_userprofile_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.TextField(null=True),
        ),
    ]
