# Generated by Django 5.1.7 on 2025-04-02 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0003_alter_userprofile_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_job',
        ),
        migrations.CreateModel(
            name='PreferredJobClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_classification', models.CharField(max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_jobs', to='myjobs.userprofile')),
            ],
        ),
    ]
