# Generated by Django 5.1.7 on 2025-04-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0004_remove_userprofile_preferred_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
