# Generated by Django 5.1.7 on 2025-04-04 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0008_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='myjobs.employer'),
            preserve_default=False,
        ),
    ]
