# Generated by Django 5.1.7 on 2025-04-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0012_applicantskill_alter_userprofile_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
