# Generated by Django 5.1.7 on 2025-04-07 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0013_jobapplication_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='ApplicantSkill',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='applicantskill',
            name='job_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_skills', to='myjobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='skill',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='myjobs.userprofile'),
        ),
    ]
