# Generated by Django 5.1.7 on 2025-04-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0014_remove_jobapplication_applicantskill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
