# Generated by Django 5.1.7 on 2025-04-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0015_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantskill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
