# Generated by Django 5.1.7 on 2025-04-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0018_job_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date_created',
            new_name='date_created_or_renewed',
        ),
    ]
