# Generated by Django 5.1.7 on 2025-04-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjobs', '0020_alter_applicantlanguageproficiency_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Data & Analytics', 'Data & Analytics'), ('Product Management', 'Product Management'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Human Resources', 'Human Resources'), ('Finance', 'Finance'), ('Customer Support', 'Customer Support')], max_length=255, null=True),
        ),
    ]
